# Notebook 04 — CMF-Static Unlearning (Paper Protocol)

**Paper:** *An Illusion of Unlearning? Assessing Machine Unlearning Through Internal Representations*  
(Gao, Unal, Rangamani, Zhu — AISTATS 2026 · arXiv:2604.08271v1)

**Protocol & Overview:**
- Loads `theta_o_state` from NB1 into a proper `ModelModule` (with CMF head).
- Runs `run_cmf_static()` (paper-faithful Algorithm 2: per-epoch recompute_cmf → freeze W → update encoder) for all 5 base methods:
  `grad_ascent_descent`, `random_label`, `salun`, `scrub`, `tarun`.
- Hyperparameters exclusively from Table 4 (`paper_hparams.py`).
- Slices forget/retain classes across seeds / classes, records Output / Probe / NCC metrics.
- Saves self-describing checkpoints: `{base_method}_cmf_static_{mean_source}_class{forget_class}_seed{seed}.pt`.

In [1]:
import subprocess, sys
def sh(cmd, verbose=True):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if verbose and r.stdout: print(r.stdout[-4000:])
    if r.returncode != 0 and r.stderr: print('STDERR:', r.stderr[-2000:])
    return r.returncode
sh('pip install -q timm einops scikit-learn matplotlib seaborn pytorch-lightning torchmetrics')

0

In [2]:
import os, sys, json, random, math, time, copy, traceback
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib; import matplotlib.pyplot as plt
matplotlib.rcParams.update({'figure.dpi': 110})
print('PyTorch:', torch.__version__, '  CUDA:', torch.cuda.is_available())

PyTorch: 2.10.0+cu128   CUDA: True


In [3]:
REPO_DIR = '/kaggle/working/CMF_Unlearning'
if not os.path.isdir(REPO_DIR):
    sh(f'git clone https://github.com/tiensinh2/CMF_Unlearning.git {REPO_DIR}')
else:
    sh(f'git -C {REPO_DIR} remote set-url origin https://github.com/tiensinh2/CMF_Unlearning.git')
    sh(f'git -C {REPO_DIR} pull origin main')
os.chdir(REPO_DIR); sys.path.insert(0, REPO_DIR)
result = subprocess.run(['git', '-C', REPO_DIR, 'rev-parse', 'HEAD'],
                        capture_output=True, text=True)
REPO_COMMIT = result.stdout.strip() or 'main'
print('Repo commit:', REPO_COMMIT)

Repo commit: 532c642deae6b1d27e88d0ae6a7070b8264a1ad2


In [4]:
CKPT_DATASET_DIR = '/kaggle/input/datasets/btk23021592/cmf-notebook1'
_CONFIG_CANDIDATES = [
    f'{CKPT_DATASET_DIR}/cmf_benchmark_config.json',
    f'{CKPT_DATASET_DIR}/checkpoints/cmf_benchmark/cmf_benchmark_config.json',
    f'{CKPT_DATASET_DIR}/cmf_benchmark/cmf_benchmark_config.json',
    './notebooks/Result_nb1/checkpoints/regun/regun_config.json',
]
config_path = CKPT_ROOT_NB1 = None
for _p in _CONFIG_CANDIDATES:
    if os.path.exists(_p):
        config_path = _p; CKPT_ROOT_NB1 = os.path.dirname(_p); break

if config_path and os.path.exists(config_path):
    with open(config_path) as f: NB1_CFG = json.load(f)
    DATASET     = NB1_CFG.get('dataset', 'cifar10')
    ARCH        = NB1_CFG.get('arch', 'resnet18')
    NUM_CLASSES = NB1_CFG.get('num_classes', 10)
    TEST_MODE   = NB1_CFG.get('test_mode', False)
else:
    DATASET     = 'cifar10'
    ARCH        = 'resnet18'
    NUM_CLASSES = 10
    TEST_MODE   = False
    CKPT_ROOT_NB1 = '/kaggle/working/checkpoints/cmf_benchmark'

STAGE = '4a'
FORGET_CLASSES = list(range(NUM_CLASSES))
SEEDS          = [0]
THETA_O_SEED   = 0
BASE_METHODS   = ['grad_ascent_descent', 'random_label', 'salun', 'scrub', 'tarun']
MEAN_SOURCES   = ['train']

# Hyperparameters from Table 4 (paper_hparams.py)
CMF_EPOCHS_BY_METHOD = {
    'random_label':        1 if TEST_MODE else 4,
    'salun':               1 if TEST_MODE else 4,
    'grad_ascent_descent': 1 if TEST_MODE else 3,
    'scrub':               1 if TEST_MODE else 3,
    'tarun':               1 if TEST_MODE else 3,
}
CMF_LR = {
    'random_label':        2e-3,
    'salun':               2e-3,
    'grad_ascent_descent': 1e-4,
    'scrub':               5e-3,
    'tarun':               5e-5,
}
CMF_BATCH = {
    'scrub': 64,
}
CMF_BATCH_DEFAULT = 128

CKPT_ROOT = '/kaggle/working/checkpoints/cmf_paper'
os.makedirs(f'{CKPT_ROOT}/cmf_static', exist_ok=True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'STAGE={STAGE}  DATASET={DATASET}  ARCH={ARCH}  device={device}')
print(f'CMF_EPOCHS_BY_METHOD={CMF_EPOCHS_BY_METHOD}')

STAGE=4a  DATASET=cifar10  ARCH=resnet18  device=cuda
CMF_EPOCHS_BY_METHOD={'random_label': 4, 'salun': 4, 'grad_ascent_descent': 3, 'scrub': 3, 'tarun': 3}


In [5]:
import torchvision, torchvision.transforms as transforms
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4), transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

full_train      = torchvision.datasets.CIFAR10('/kaggle/working/data', train=True,
                                               download=True,  transform=transform_train)
full_train_eval = torchvision.datasets.CIFAR10('/kaggle/working/data', train=True,
                                               download=False, transform=transform_test)
test_set        = torchvision.datasets.CIFAR10('/kaggle/working/data', train=False,
                                               download=True, transform=transform_test)

# Pre-index by class label
test_targets = torch.tensor(test_set.targets)
TEST_CLASS_IDX = {
    c: (test_targets == c).nonzero(as_tuple=True)[0].tolist()
    for c in range(NUM_CLASSES)
}
train_targets = torch.tensor(full_train.targets)
TRAIN_CLASS_IDX = {
    c: (train_targets == c).nonzero(as_tuple=True)[0].tolist()
    for c in range(NUM_CLASSES)
}
print(f'Train size: {len(full_train)}  Test size: {len(test_set)}')

100%|██████████| 170M/170M [45:13<00:00, 62.8kB/s]


Train size: 50000  Test size: 10000


In [6]:
import argparse
from unlearn.cmf_weights import ModelModule
from unlearn.cmf_two_stage import run_cmf_static

def build_cmf_model(args):
    """Construct proper ModelModule with CMF classifier head."""
    model = ModelModule(args).to(device)
    assert hasattr(model, 'CMFweights'), 'Model must have CMFweights attribute!'
    return model

def make_cmf_args(base_method, lr, epochs, mean_source, forget_class,
                  forget_train_idx, retain_train_idx, seed=0):
    return argparse.Namespace(
        dataset=DATASET, arch=ARCH, num_classes=NUM_CLASSES,
        class_label_names=list(range(NUM_CLASSES)),
        unlearn_method=f'{base_method}_CMF_RemoveFC',
        unlearn_class=[forget_class],
        batch_size=128, test_batch_size=256, lr=lr,
        momentum=0.9, weight_decay=5e-4, epochs_or_steps=epochs,
        seed=seed,
        num_retain_samples=len(retain_train_idx),
        num_forget_samples=len(forget_train_idx),
        grad_norm_clip=1.0,
        SVD_alpha_r=1000, SVD_alpha_f=30,
        SVD_samples=900, SVD_max_patches=10000,
        freeze_except_last=False,
        scrub_del_bsz=64, scrub_sgda_bsz=64, scrub_msteps=2, scrub_epochs=epochs,
        salun_threshold=0.5,
        tarun_impair_lr=lr, tarun_samples_per_class=1000,
        dry_run=TEST_MODE, no_cuda=False, no_mps=True, gamma=0.5,
        data_path='/kaggle/working/data', remove_FC=True,
        CMFClassifier=True, CMF_momentum=0.9, pretrained=False, temperature=1.0,
        prob_batch_size=256, lp_every=0, mean_source=mean_source,
        repo_commit=REPO_COMMIT, test_mode=TEST_MODE,
    )

@torch.no_grad()
def eval_acc(model, loader):
    model.eval()
    correct = total = 0
    for x, y in loader:
        correct += (model(x.to(device)).argmax(1).cpu() == y).sum().item()
        total   += y.size(0)
    return 100.0 * correct / max(total, 1)

@torch.no_grad()
def cmf_extract_features(model, loader):
    model.eval()
    feats, labs = [], []
    for x, y in loader:
        x = x.to(device)
        f = model.extract_features(x)
        z = model._preprocess_feats_for_cmf(f)
        feats.append(z.cpu()); labs.append(y)
    return torch.cat(feats), torch.cat(labs)

def run_probe_cmf(model, train_retain_ldr, train_forget_ldr,
                  test_retain_ldr, test_forget_ldr, n_epochs=50):
    Xtr, ytr = cmf_extract_features(model, train_retain_ldr)
    Xfg, yfg = cmf_extract_features(model, train_forget_ldr)
    Xall = torch.cat([Xtr, Xfg])
    yall = torch.cat([ytr, yfg])
    head = nn.Linear(Xall.size(1), NUM_CLASSES).to(device)
    opt  = optim.SGD(head.parameters(), lr=1e-2, momentum=0.9)
    ldr  = torch.utils.data.DataLoader(
               torch.utils.data.TensorDataset(Xall, yall), batch_size=256, shuffle=True)
    for _ in range(n_epochs):
        head.train()
        for bx, by in ldr:
            opt.zero_grad()
            F.cross_entropy(head(bx.to(device)), by.to(device)).backward()
            opt.step()
    head.eval()
    with torch.no_grad():
        Xte_r, yte_r = cmf_extract_features(model, test_retain_ldr)
        Xte_f, yte_f = cmf_extract_features(model, test_forget_ldr)
        ret_acc = (head(Xte_r.to(device)).argmax(1).cpu() == yte_r).float().mean().item() * 100
        fgt_acc = (head(Xte_f.to(device)).argmax(1).cpu() == yte_f).float().mean().item() * 100
    return ret_acc, fgt_acc

def run_ncc_cmf(model, train_retain_ldr, train_forget_ldr,
                test_retain_ldr, test_forget_ldr):
    Xtr, ytr = cmf_extract_features(model, train_retain_ldr)
    Xfg, yfg = cmf_extract_features(model, train_forget_ldr)
    Xall = torch.cat([Xtr, Xfg])
    yall = torch.cat([ytr, yfg])
    means = []
    for c in range(NUM_CLASSES):
        mask = (yall == c)
        mu = Xall[mask].mean(0) if mask.any() else torch.zeros(Xall.size(1))
        means.append(mu)
    M = torch.stack(means)
    Xte_r, yte_r = cmf_extract_features(model, test_retain_ldr)
    Xte_f, yte_f = cmf_extract_features(model, test_forget_ldr)
    ret_pred = torch.cdist(Xte_r.unsqueeze(0), M.unsqueeze(0)).squeeze(0).argmin(1)
    fgt_pred = torch.cdist(Xte_f.unsqueeze(0), M.unsqueeze(0)).squeeze(0).argmin(1)
    return ((ret_pred == yte_r).float().mean().item() * 100,
            (fgt_pred == yte_f).float().mean().item() * 100)

def eval_cmf_three_metrics(model,
                           test_retain_ldr, test_forget_ldr,
                           train_retain_eval_ldr, train_forget_eval_ldr):
    out_ret = eval_acc(model, test_retain_ldr)
    out_fgt = eval_acc(model, test_forget_ldr)
    lp_ret, lp_fgt   = run_probe_cmf(model, train_retain_eval_ldr, train_forget_eval_ldr,
                                      test_retain_ldr, test_forget_ldr)
    ncc_ret, ncc_fgt = run_ncc_cmf(model, train_retain_eval_ldr, train_forget_eval_ldr,
                                    test_retain_ldr, test_forget_ldr)
    return {'output_retain_acc': out_ret, 'output_forget_acc': out_fgt,
            'probe_retain_acc':  lp_ret,  'probe_forget_acc':  lp_fgt,
            'ncc_retain_acc':    ncc_ret, 'ncc_forget_acc':    ncc_fgt}

print('Helpers ready.')

Helpers ready.


In [7]:
# ── Load theta_o ────────────────────────────────────────────────────────────
theta_o_candidates = [
    f'{CKPT_ROOT_NB1}/pre_train/theta_o_seed{THETA_O_SEED}.pt',
    f'{CKPT_ROOT_NB1}/pre_train/cifar10_resnet18_full.pt',
    './notebooks/Result_nb1/checkpoints/regun/pre_train/cifar10_resnet18_full.pt',
]
theta_o_path = None
for _p in theta_o_candidates:
    if os.path.exists(_p):
        theta_o_path = _p; break
if theta_o_path is None and os.path.exists('./checkpoints/pre_train/cifar10_resnet18_full.pt'):
    theta_o_path = './checkpoints/pre_train/cifar10_resnet18_full.pt'

if theta_o_path and os.path.exists(theta_o_path):
    print(f'Loading theta_o from {theta_o_path}')
    ck_o = torch.load(theta_o_path, map_location=device)
    theta_o_state = ck_o.get('model_state_dict', ck_o)
else:
    print('WARNING: theta_o checkpoint not found. Creating initialized backbone state.')
    from models.resnet import ResNet18
    _init_m = ResNet18(num_classes=NUM_CLASSES, dataset=DATASET)
    theta_o_state = _init_m.state_dict()

results_4a = []

for forget_class in FORGET_CLASSES:
    for seed in SEEDS:
        forget_train_idx = TRAIN_CLASS_IDX[forget_class]
        retain_train_idx = [
            i for c in range(NUM_CLASSES)
            if c != forget_class
            for i in TRAIN_CLASS_IDX[c]
        ]
        retain_loader = torch.utils.data.DataLoader(
            torch.utils.data.Subset(full_train, retain_train_idx),
            batch_size=128, shuffle=True, num_workers=2)
        forget_loader = torch.utils.data.DataLoader(
            torch.utils.data.Subset(full_train, forget_train_idx),
            batch_size=128, shuffle=True, num_workers=2)
        full_train_loader = torch.utils.data.DataLoader(
            full_train, batch_size=256, shuffle=False, num_workers=2)
        train_retain_eval_ldr = torch.utils.data.DataLoader(
            torch.utils.data.Subset(full_train_eval, retain_train_idx),
            batch_size=256, shuffle=False, num_workers=2)
        train_forget_eval_ldr = torch.utils.data.DataLoader(
            torch.utils.data.Subset(full_train_eval, forget_train_idx),
            batch_size=256, shuffle=False, num_workers=2)
        test_forget_idx = TEST_CLASS_IDX[forget_class]
        test_retain_idx = [
            i for c in range(NUM_CLASSES)
            if c != forget_class
            for i in TEST_CLASS_IDX[c]
        ]
        test_forget_ldr = torch.utils.data.DataLoader(
            torch.utils.data.Subset(test_set, test_forget_idx),
            batch_size=256, shuffle=False, num_workers=2)
        test_retain_ldr = torch.utils.data.DataLoader(
            torch.utils.data.Subset(test_set, test_retain_idx),
            batch_size=256, shuffle=False, num_workers=2)
        test_loader_full = torch.utils.data.DataLoader(
            test_set, batch_size=256, shuffle=False, num_workers=2)

        for base_method in BASE_METHODS:
            for mean_source in MEAN_SOURCES:
                cmf_epochs = CMF_EPOCHS_BY_METHOD.get(base_method, 3)
                lr    = CMF_LR.get(base_method, 1e-3)
                batch = CMF_BATCH.get(base_method, CMF_BATCH_DEFAULT)
                tag   = f'{base_method}_cmf_static_{mean_source}_class{forget_class}_seed{seed}'
                if TEST_MODE: tag += '_testmode'
                ckpt_path = f'{CKPT_ROOT}/cmf_static/{tag}.pt'

                if os.path.exists(ckpt_path):
                    print(f'[{tag}] exists — loading cached result.')
                    ck = torch.load(ckpt_path, map_location=device)
                    results_4a.append(ck['metrics'])
                    continue

                print(f'\n[{tag}] Running cmf_static ({base_method}) for {cmf_epochs} epochs...')
                torch.manual_seed(seed); np.random.seed(seed); random.seed(seed)

                args = make_cmf_args(base_method, lr, cmf_epochs, mean_source,
                                     forget_class, forget_train_idx, retain_train_idx,
                                     seed=seed)
                args.batch_size = batch
                if base_method == 'scrub':
                    args.scrub_del_bsz  = 64
                    args.scrub_sgda_bsz = 64

                model = build_cmf_model(args)
                model.encoder.load_state_dict(theta_o_state, strict=False)

                mean_loader = full_train_loader if mean_source == 'train' else retain_loader
                model.eval()
                model.recompute_cmf(mean_loader, device=device)

                t0 = time.time()
                try:
                    model = run_cmf_static(
                        base_method=base_method,
                        args=args,
                        model=model,
                        device=device,
                        retain_loader=retain_loader,
                        forget_loader=forget_loader,
                        train_loader=mean_loader,
                        test_loader=test_loader_full,
                        epochs=cmf_epochs,
                        test_forget_loader=test_forget_ldr,
                        train_dataset=full_train,
                        val_index=retain_train_idx,
                    )
                except Exception as e:
                    print(f'ERROR running {base_method}: {e}')
                    traceback.print_exc()
                    continue
                wall_min = (time.time() - t0) / 60

                model.eval()
                model.recompute_cmf(mean_loader, device=device)

                metrics = eval_cmf_three_metrics(
                    model,
                    test_retain_ldr, test_forget_ldr,
                    train_retain_eval_ldr, train_forget_eval_ldr
                )
                metrics.update({
                    'method': base_method, 'mean_source': mean_source,
                    'forget_class': forget_class, 'seed': seed, 'stage': STAGE,
                    'cmf_epochs': cmf_epochs, 'lr': lr, 'batch': batch,
                    'wall_clock_minutes': wall_min,
                    'n_forget_train': len(forget_train_idx),
                    'n_retain_train': len(retain_train_idx),
                    'protocol': 'whole_class_single',
                })

                torch.save({
                    'model_state_dict': model.state_dict(),
                    'config': {
                        'base_method': base_method, 'mean_source': mean_source,
                        'dataset': DATASET, 'arch': ARCH, 'num_classes': NUM_CLASSES,
                        'forget_class': forget_class, 'seed': seed,
                        'cmf_epochs': cmf_epochs, 'lr': lr, 'batch': batch,
                        'protocol': 'whole_class_single',
                        'repo_commit': REPO_COMMIT, 'test_mode': TEST_MODE,
                    },
                    'seed': seed, 'metrics': metrics,
                }, ckpt_path)
                print(f'  Saved {ckpt_path}')
                print(f'  out  R={metrics["output_retain_acc"]:.2f}%  F={metrics["output_forget_acc"]:.2f}%')
                print(f'  probe R={metrics["probe_retain_acc"]:.2f}%  F={metrics["probe_forget_acc"]:.2f}%')
                print(f'  ncc  R={metrics["ncc_retain_acc"]:.2f}%  F={metrics["ncc_forget_acc"]:.2f}%')
                results_4a.append(metrics)

df_4a = pd.DataFrame(results_4a)
csv_path = f'{CKPT_ROOT}/results_4a_cmf_static.csv'
df_4a.to_csv(csv_path, index=False)
print(f'\nResults saved to {csv_path}')
if not df_4a.empty:
    metric_cols = ['output_retain_acc','output_forget_acc',
                   'probe_retain_acc','probe_forget_acc','ncc_retain_acc','ncc_forget_acc']
    print('\n=== Summary ===')
    print(df_4a.groupby('method')[metric_cols].mean().round(2).to_string())

Loading theta_o from /kaggle/input/datasets/btk23021592/cmf-notebook1/checkpoints/cmf_benchmark/pre_train/theta_o_seed0.pt

[grad_ascent_descent_cmf_static_train_class0_seed0] Running cmf_static (grad_ascent_descent) for 3 epochs...
Removing FC layer from the encoder and using CMF classifier.
CMF_momentum: 0.9
[ModelModule] arch=resnet18, is_vit=False, remove_FC=True, feature_dim=512
[Before Unlearning] Evaluating CMF model
args.CMF_momentum = 0.9
model.args.CMF_momentum = 0.9
Test Set (Epoch 0): Average loss: 1.4400, Accuracy: 9445/10000 (94%)
------------------------------
Test Set (Epoch 0) Confusion Matrix 
[[962.   1.  12.   0.   1.   2.   1.   1.  18.   2.]
 [  5. 974.   0.   0.   0.   0.   0.   1.   4.  16.]
 [ 13.   0. 917.  11.  19.  13.  19.   4.   4.   0.]
 [  4.   1.  17. 879.  13.  59.  15.   4.   5.   3.]
 [  2.   0.   7.  15. 957.   2.  10.   6.   1.   0.]
 [  3.   1.  10.  54.  12. 907.   2.   8.   1.   2.]
 [  6.   1.   8.  13.   3.   3. 965.   1.   0.   0.]
 [  7.   2

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 99.040 
Test Set (Epoch 1): Average loss: 1.4794, Accuracy: 8925/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[538.  37. 176.  54.  43.  10.  10.  19.  74.  39.]
 [  0. 984.   1.   1.   0.   1.   0.   0.   2.  11.]
 [  1.   2. 894.  18.  36.  12.  22.  11.   4.   0.]
 [  1.   3.  12. 902.  18.  37.  17.   6.   3.   1.]
 [  0.   0.   7.  11. 958.   1.  10.  12.   1.   0.]
 [  0.   1.   6. 105.  15. 847.  12.  12.   0.   2.]
 [  0.   1.  11.  19.   6.   1. 961.   0.   0.   1.]
 [  0.   1.   5.  18.  12.  11.   1. 950.   2.   0.]
 [  1.  15.   3.   6.   2.   1.   3.   1. 964.   4.]
 [  1.  60.   1.   6.   0.   0.   0.   0.   5. 927.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(53.800000000000004), 1: np.float64(98.4), 2: np.float64(89.4), 3: np.float64(90.2), 4: np.float64(95.8), 5: np.float64(84.7), 6: np.float64(96.1), 7: np.float64(95.0), 8: np.float64(96.39999999999999), 9: np.float64(92.7)}
-----------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.413 
Test Set (Epoch 2): Average loss: 1.4986, Accuracy: 8619/10000 (86%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[297.  26. 228.  98.  56.   6.  28.  19. 184.  58.]
 [  0. 973.   2.   4.   0.   0.   2.   0.   5.  14.]
 [  0.   0. 897.  24.  22.  20.  25.   5.   7.   0.]
 [  0.   0.  24. 871.  10.  63.  17.   7.   6.   2.]
 [  0.   0.  10.  18. 948.   5.  11.   7.   1.   0.]
 [  0.   0.   4.  81.  20. 886.   4.   5.   0.   0.]
 [  0.   1.  19.  21.   2.   2. 953.   1.   0.   1.]
 [  0.   2.  10.  24.  54.  19.   0. 888.   2.   1.]
 [  0.  12.   4.   7.   3.   0.   2.   2. 964.   6.]
 [  0.  38.   1.   7.   0.   0.   1.   0.  11. 942.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(29.7), 1: np.float64(97.3), 2: np.float64(89.7), 3: np.float64(87.1), 4: np.float64(94.8), 5: np.float64(88.6), 6: np.float64(95.3), 7: np.float64(88.8), 8: np.float64(96.39999999999999), 9: np.float64(94.19999999999999)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.262 
Test Set (Epoch 3): Average loss: 1.5085, Accuracy: 8464/10000 (85%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[222.  40. 266. 109.  46.   4.   4.  30. 241.  38.]
 [  0. 969.   1.   3.   1.   2.   1.   1.   7.  15.]
 [  0.   0. 870.  52.  31.  12.  18.   8.   9.   0.]
 [  0.   1.  11. 914.  14.  38.   6.   7.   6.   3.]
 [  0.   1.  10.  26. 934.   5.  14.   8.   1.   1.]
 [  0.   1.   7. 133.  15. 835.   1.   6.   1.   1.]
 [  0.   1.  23.  37.   3.   3. 930.   1.   2.   0.]
 [  0.   1.   4.  38.  21.  21.   0. 912.   3.   0.]
 [  0.  10.   2.   7.   0.   0.   3.   0. 977.   1.]
 [  0.  55.   2.  12.   1.   1.   0.   1.  27. 901.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(22.2), 1: np.float64(96.89999999999999), 2: np.float64(87.0), 3: np.float64(91.4), 4: np.float64(93.4), 5: np.float64(83.5), 6: np.float64(93.0), 7: np.float64(91.2), 8: np.float64(97.7), 9: np.float64(90.10000000000001)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.889 
Test Set (Epoch 1): Average loss: 1.4702, Accuracy: 8932/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[901.   0.  16.   8.  15.   4.   7.   5.  38.   6.]
 [ 14. 576.   1.   6.   2.   2.   6.   2.  58. 333.]
 [  9.   0. 882.  20.  31.  17.  27.   9.   4.   1.]
 [  1.   0.  15. 846.  29.  77.  23.   5.   3.   1.]
 [  1.   0.   3.  10. 965.   5.   9.   6.   1.   0.]
 [  1.   0.   7.  51.  14. 905.   6.  14.   2.   0.]
 [  4.   0.   7.  14.   5.   6. 962.   1.   0.   1.]
 [  2.   0.   2.   9.  19.  20.   0. 945.   1.   2.]
 [  9.   0.   4.   2.   1.   0.   2.   1. 970.  11.]
 [  4.   0.   1.   5.   0.   1.   0.   1.   8. 980.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(90.10000000000001), 1: np.float64(57.599999999999994), 2: np.float64(88.2), 3: np.float64(84.6), 4: np.float64(96.5), 5: np.float64(90.5), 6: np.float64(96.2), 7: np.float64(94.5), 8: np.float64(97.0), 9: np.float64(98.0)}
-----------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.296 
Test Set (Epoch 2): Average loss: 1.5067, Accuracy: 8511/10000 (85%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[907.   1.  18.  14.  11.   1.  18.   1.  28.   1.]
 [ 61. 373.   9.  26.   3.   1. 107.   0. 151. 269.]
 [ 16.   0. 865.  33.  24.   7.  49.   2.   2.   2.]
 [  8.   0.  19. 853.  14.  32.  64.   3.   6.   1.]
 [  4.   0.   9.  25. 935.   4.  20.   3.   0.   0.]
 [  5.   0.  13. 121.  14. 815.  28.   3.   1.   0.]
 [  3.   0.   6.   6.   1.   0. 984.   0.   0.   0.]
 [  6.   0.  12.  39.  27.  23.   7. 883.   2.   1.]
 [ 18.   3.   5.   4.   1.   0.   4.   0. 962.   3.]
 [ 16.  16.   1.  11.   0.   1.   5.   2.  14. 934.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(90.7), 1: np.float64(37.3), 2: np.float64(86.5), 3: np.float64(85.3), 4: np.float64(93.5), 5: np.float64(81.5), 6: np.float64(98.4), 7: np.float64(88.3), 8: np.float64(96.2), 9: np.float64(93.4)}
------------------------------
Test Se

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 97.787 
Test Set (Epoch 3): Average loss: 1.5030, Accuracy: 8474/10000 (85%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[942.   1.  10.   8.   9.   1.   1.   1.  27.   0.]
 [156. 330.   2.   9.   4.   5.  11.   0. 236. 247.]
 [ 38.   0. 833.  51.  36.  14.  17.   6.   4.   1.]
 [ 12.   0.  15. 897.  16.  38.  10.   5.   7.   0.]
 [  6.   0.   3.  20. 951.   4.  11.   5.   0.   0.]
 [  5.   0.  13. 113.  20. 832.   6.   9.   1.   1.]
 [  8.   0.  16.  43.   5.   6. 918.   1.   1.   2.]
 [ 15.   0.   9.  22.  36.  15.   1. 899.   3.   0.]
 [ 15.   2.   2.   3.   1.   1.   2.   0. 974.   0.]
 [ 30.  15.   2.   7.   0.   1.   0.   0.  47. 898.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(94.19999999999999), 1: np.float64(33.0), 2: np.float64(83.3), 3: np.float64(89.7), 4: np.float64(95.1), 5: np.float64(83.2), 6: np.float64(91.8), 7: np.float64(89.9), 8: np.float64(97.39999999999999), 9: np.float64(89.8)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 99.056 
Test Set (Epoch 1): Average loss: 1.4775, Accuracy: 8945/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[947.   5.   0.   3.   7.   5.   3.   4.  17.   9.]
 [  2. 962.   0.   0.   0.   1.   0.   4.   5.  26.]
 [ 92.   2. 527.  45. 133.  67.  62.  56.  11.   5.]
 [  8.   1.   0. 781.  29. 136.  17.  15.   7.   6.]
 [  5.   0.   0.  13. 946.  11.   3.  22.   0.   0.]
 [  5.   1.   0.  36.  16. 921.   3.  16.   1.   1.]
 [  4.   0.   1.  15.  17.   4. 954.   4.   0.   1.]
 [  1.   0.   0.   4.   9.   7.   0. 977.   2.   0.]
 [ 19.   5.   0.   0.   2.   0.   1.   0. 966.   7.]
 [  5.  19.   0.   2.   0.   2.   0.   1.   7. 964.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(94.69999999999999), 1: np.float64(96.2), 2: np.float64(52.7), 3: np.float64(78.10000000000001), 4: np.float64(94.6), 5: np.float64(92.10000000000001), 6: np.float64(95.39999999999999), 7: np.float64(97.7), 8: np.float64(96.6), 9: np.f

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.584 
Test Set (Epoch 2): Average loss: 1.4985, Accuracy: 8622/10000 (86%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[931.   3.   1.   6.   4.   1.   5.   4.  30.  15.]
 [  4. 933.   0.   1.   0.   1.   2.   1.   6.  52.]
 [155.   1. 244. 160. 156.  54. 161.  48.  12.   9.]
 [  7.   0.   1. 870.  18.  49.  32.  11.   8.   4.]
 [ 10.   0.   0.  17. 942.   4.  16.  11.   0.   0.]
 [  5.   1.   0.  92.  20. 849.  10.  16.   4.   3.]
 [  5.   0.   0.  11.   7.   2. 969.   4.   1.   1.]
 [  3.   0.   0.  19.  20.   6.   2. 946.   2.   2.]
 [ 14.   6.   0.   5.   0.   0.   4.   0. 962.   9.]
 [  2.   8.   0.   1.   0.   0.   0.   1.  12. 976.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(93.10000000000001), 1: np.float64(93.30000000000001), 2: np.float64(24.4), 3: np.float64(87.0), 4: np.float64(94.19999999999999), 5: np.float64(84.89999999999999), 6: np.float64(96.89999999999999), 7: np.float64(94.6), 8: np.float64(9

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.024 
Test Set (Epoch 3): Average loss: 1.5085, Accuracy: 8531/10000 (85%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[945.   2.   0.   7.   9.   1.   1.   3.  30.   2.]
 [  8. 951.   0.   0.   1.   0.   2.   0.  13.  25.]
 [186.   7. 271.  84. 189.  69. 128.  40.  21.   5.]
 [ 16.   3.   0. 813.  43.  71.  33.   9.   7.   5.]
 [  6.   0.   0.  11. 959.   1.  14.   8.   1.   0.]
 [  8.   1.   0.  80.  31. 851.  10.  16.   0.   3.]
 [  9.   0.   1.  18.  12.   3. 951.   1.   2.   3.]
 [ 13.   3.   0.  16.  36.  15.   3. 906.   4.   4.]
 [ 20.   4.   0.   3.   1.   0.   5.   1. 966.   0.]
 [ 15.  31.   0.   3.   1.   1.   3.   1.  27. 918.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(94.5), 1: np.float64(95.1), 2: np.float64(27.1), 3: np.float64(81.3), 4: np.float64(95.89999999999999), 5: np.float64(85.1), 6: np.float64(95.1), 7: np.float64(90.60000000000001), 8: np.float64(96.6), 9: np.float64(91.8)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 99.233 
Test Set (Epoch 1): Average loss: 1.4712, Accuracy: 8875/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[936.   3.  11.   0.   4.   0.   4.   5.  26.  11.]
 [  2. 960.   0.   0.   0.   0.   0.   0.   5.  33.]
 [ 26.   0. 864.   0.  46.  15.  35.   9.   5.   0.]
 [ 26.   5.  48. 358.  92. 359.  58.  31.  12.  11.]
 [  2.   0.   5.   0. 975.   2.   9.   6.   0.   1.]
 [  5.   3.  11.   1.  35. 920.   6.  17.   2.   0.]
 [  5.   0.  12.   1.  13.   6. 962.   0.   0.   1.]
 [  3.   1.   3.   0.  24.  12.   2. 953.   1.   1.]
 [ 11.   3.   2.   0.   0.   0.   3.   1. 974.   6.]
 [  5.  13.   0.   0.   0.   0.   2.   0.   7. 973.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(93.60000000000001), 1: np.float64(96.0), 2: np.float64(86.4), 3: np.float64(35.8), 4: np.float64(97.5), 5: np.float64(92.0), 6: np.float64(96.2), 7: np.float64(95.3), 8: np.float64(97.39999999999999), 9: np.float64(97.3)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.809 
Test Set (Epoch 2): Average loss: 1.4910, Accuracy: 8724/10000 (87%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[955.   3.   6.   0.   2.   2.   4.   3.  24.   1.]
 [ 10. 946.   1.   0.   0.   2.   7.   1.  13.  20.]
 [ 29.   0. 891.   0.  15.  16.  33.  10.   6.   0.]
 [ 64.   3. 121. 292.  41. 268. 156.  30.  14.  11.]
 [ 16.   0.  14.   0. 930.   4.  27.   7.   2.   0.]
 [  8.   1.  19.   4.  21. 909.  20.  12.   3.   3.]
 [  5.   0.   6.   0.   3.   2. 982.   1.   1.   0.]
 [  8.   0.   8.   0.  36.  28.   4. 913.   2.   1.]
 [ 20.   2.   1.   0.   0.   3.   4.   0. 966.   4.]
 [ 12.  28.   1.   0.   0.   1.   4.   0.  14. 940.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(95.5), 1: np.float64(94.6), 2: np.float64(89.1), 3: np.float64(29.2), 4: np.float64(93.0), 5: np.float64(90.9), 6: np.float64(98.2), 7: np.float64(91.3), 8: np.float64(96.6), 9: np.float64(94.0)}
------------------------------
Test Se

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.740 
Test Set (Epoch 3): Average loss: 1.4849, Accuracy: 8697/10000 (87%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[926.   6.  32.   1.   5.   4.   5.   4.  15.   2.]
 [  3. 964.   0.   0.   0.   2.   3.   0.   6.  22.]
 [ 14.   0. 919.   4.  28.  17.  14.   2.   2.   0.]
 [ 24.   5. 121. 332.  55. 367.  58.  26.   6.   6.]
 [  1.   0.  23.   1. 934.  14.  15.  12.   0.   0.]
 [  5.   2.  26.  22.  17. 904.  10.  13.   0.   1.]
 [  5.   0.  41.   0.   7.  12. 933.   0.   1.   1.]
 [  6.   0.  10.   4.  14.  21.   5. 935.   3.   2.]
 [ 23.  11.  14.   0.   1.   1.   3.   3. 938.   6.]
 [  9.  48.   4.   0.   3.   1.   5.   1.  17. 912.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(92.60000000000001), 1: np.float64(96.39999999999999), 2: np.float64(91.9), 3: np.float64(33.2), 4: np.float64(93.4), 5: np.float64(90.4), 6: np.float64(93.30000000000001), 7: np.float64(93.5), 8: np.float64(93.8), 9: np.float64(91.2)}

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.984 
Test Set (Epoch 1): Average loss: 1.4853, Accuracy: 8863/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[965.   1.   8.   4.   0.   2.   8.   4.   6.   2.]
 [  3. 972.   0.   0.   0.   1.   0.   0.   5.  19.]
 [ 33.   0. 896.  19.   2.   9.  29.   8.   3.   1.]
 [  7.   2.  22. 861.   0.  52.  33.  15.   6.   2.]
 [ 43.   0.  98.  80. 472.  66.  85. 147.   9.   0.]
 [  5.   0.  18.  77.   0. 864.   7.  26.   1.   2.]
 [  3.   0.  17.  11.   0.   2. 966.   0.   1.   0.]
 [  7.   0.   7.   8.   0.  15.   1. 962.   0.   0.]
 [ 34.   7.   4.   0.   0.   1.   2.   0. 946.   6.]
 [  5.  23.   2.   1.   0.   0.   2.   0.   8. 959.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(96.5), 1: np.float64(97.2), 2: np.float64(89.60000000000001), 3: np.float64(86.1), 4: np.float64(47.199999999999996), 5: np.float64(86.4), 6: np.float64(96.6), 7: np.float64(96.2), 8: np.float64(94.6), 9: np.float64(95.89999999999999)

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.329 
Test Set (Epoch 2): Average loss: 1.5146, Accuracy: 8483/10000 (85%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[885.   5.  33.   7.   1.   0.  20.   1.  19.  29.]
 [  1. 938.   1.   0.   0.   0.   4.   1.   6.  49.]
 [  6.   0. 931.  14.   0.   1.  38.   3.   5.   2.]
 [  3.   0.  36. 859.   2.  21.  62.   5.   2.  10.]
 [ 37.   2. 191. 139. 313.  18. 149. 128.  10.  13.]
 [  3.   2.  33. 146.   2. 731.  49.  27.   0.   7.]
 [  2.   0.  12.   4.   0.   0. 980.   1.   0.   1.]
 [  4.   0.  14.  27.   0.   3.   8. 936.   2.   6.]
 [ 16.   5.   5.   3.   1.   0.  15.   0. 939.  16.]
 [  2.  15.   3.   0.   0.   0.   1.   0.   8. 971.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(88.5), 1: np.float64(93.8), 2: np.float64(93.10000000000001), 3: np.float64(85.9), 4: np.float64(31.3), 5: np.float64(73.1), 6: np.float64(98.0), 7: np.float64(93.60000000000001), 8: np.float64(93.89999999999999), 9: np.float64(97.1)}

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 97.622 
Test Set (Epoch 3): Average loss: 1.5178, Accuracy: 8379/10000 (84%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[929.   5.  38.   5.   0.   1.   4.   0.  15.   3.]
 [  8. 972.   0.   1.   0.   0.   0.   0.   2.  17.]
 [  9.   0. 934.  23.  11.   7.  12.   1.   3.   0.]
 [ 16.   1.  37. 868.   6.  34.  29.   2.   4.   3.]
 [ 66.   7. 263. 169. 274.  93.  76.  49.   3.   0.]
 [  9.   0.  39. 172.  13. 746.  16.   4.   0.   1.]
 [  6.   1.  26.  14.   1.   2. 950.   0.   0.   0.]
 [ 23.   1.  36.  36.   2.  43.   3. 856.   0.   0.]
 [ 44.   7.   4.   1.   0.   1.   6.   0. 930.   7.]
 [ 22.  45.   1.   3.   0.   0.   1.   0.   8. 920.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(92.9), 1: np.float64(97.2), 2: np.float64(93.4), 3: np.float64(86.8), 4: np.float64(27.400000000000002), 5: np.float64(74.6), 6: np.float64(95.0), 7: np.float64(85.6), 8: np.float64(93.0), 9: np.float64(92.0)}
------------------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 99.142 
Test Set (Epoch 1): Average loss: 1.4789, Accuracy: 8875/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[908.   5.  18.   9.   4.   0.   6.   1.  34.  15.]
 [  2. 959.   1.   0.   0.   0.   1.   0.   4.  33.]
 [ 13.   0. 888.  25.  28.   0.  32.   8.   6.   0.]
 [  4.   2.  18. 876.  32.   1.  43.  10.   8.   6.]
 [  1.   0.   4.  11. 959.   0.  15.   8.   2.   0.]
 [  4.   3.  63. 317.  79. 423.  56.  46.   6.   3.]
 [  1.   0.   4.   4.   5.   0. 985.   0.   0.   1.]
 [  4.   2.   5.  18.  22.   0.   7. 938.   2.   2.]
 [ 12.   5.   2.   0.   1.   0.   3.   0. 967.  10.]
 [  3.  17.   0.   1.   0.   0.   1.   0.   6. 972.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(90.8), 1: np.float64(95.89999999999999), 2: np.float64(88.8), 3: np.float64(87.6), 4: np.float64(95.89999999999999), 5: np.float64(42.3), 6: np.float64(98.5), 7: np.float64(93.8), 8: np.float64(96.7), 9: np.float64(97.2)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.538 
Test Set (Epoch 2): Average loss: 1.4800, Accuracy: 8793/10000 (88%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[916.   2.  11.   4.   1.   0.  12.   3.  37.  14.]
 [  3. 955.   0.   0.   1.   0.   5.   0.   6.  30.]
 [ 18.   0. 894.  15.  23.   1.  40.   6.   3.   0.]
 [  4.   1.  40. 858.  14.   1.  65.   7.   7.   3.]
 [  3.   0.  15.  18. 926.   0.  21.  14.   2.   1.]
 [  8.   1. 110. 314.  34. 390.  72.  65.   3.   3.]
 [  3.   0.   7.   5.   1.   0. 982.   1.   0.   1.]
 [  2.   1.   7.  22.  10.   0.   5. 951.   2.   0.]
 [ 10.   6.   3.   4.   1.   0.   7.   0. 962.   7.]
 [  3.  20.   3.   2.   0.   0.   0.   1.  12. 959.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(91.60000000000001), 1: np.float64(95.5), 2: np.float64(89.4), 3: np.float64(85.8), 4: np.float64(92.60000000000001), 5: np.float64(39.0), 6: np.float64(98.2), 7: np.float64(95.1), 8: np.float64(96.2), 9: np.float64(95.89999999999999)}

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.036 
Test Set (Epoch 3): Average loss: 1.4907, Accuracy: 8683/10000 (87%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[891.   3.  41.   1.   3.   0.   2.   0.  56.   3.]
 [  5. 958.   1.   1.   0.   0.   0.   0.   9.  26.]
 [ 10.   0. 941.   9.  18.   3.  11.   3.   4.   1.]
 [  5.   4.  76. 826.  24.  16.  21.   8.  13.   7.]
 [  1.   0.  18.  10. 952.   0.   6.   7.   4.   2.]
 [  6.   1. 241. 273.  46. 365.  22.  32.  13.   1.]
 [  4.   3.  52.  11.   5.   1. 920.   0.   2.   2.]
 [  9.   1.  20.  15.  39.   0.   1. 910.   4.   1.]
 [ 10.   5.   5.   0.   0.   0.   0.   0. 974.   6.]
 [  7.  23.   3.   2.   0.   0.   1.   0.  18. 946.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(89.1), 1: np.float64(95.8), 2: np.float64(94.1), 3: np.float64(82.6), 4: np.float64(95.19999999999999), 5: np.float64(36.5), 6: np.float64(92.0), 7: np.float64(91.0), 8: np.float64(97.39999999999999), 9: np.float64(94.6)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.887 
Test Set (Epoch 1): Average loss: 1.4823, Accuracy: 8879/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[931.   6.  10.   5.   4.   3.   0.   4.  31.   6.]
 [  2. 977.   0.   0.   0.   1.   0.   0.   6.  14.]
 [ 18.   1. 904.  30.  25.  12.   0.   6.   4.   0.]
 [  4.   0.  28. 882.  18.  49.   1.  11.   7.   0.]
 [  3.   0.  18.  19. 949.   5.   0.   4.   2.   0.]
 [  5.   1.  15.  82.  15. 870.   0.  10.   2.   0.]
 [  9.  10. 198. 158.  47.  19. 531.   3.  24.   1.]
 [  5.   0.   7.  11.  24.  15.   0. 935.   3.   0.]
 [  9.  10.   3.   3.   2.   0.   0.   0. 970.   3.]
 [  5.  31.   2.   6.   1.   1.   0.   1.  23. 930.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(93.10000000000001), 1: np.float64(97.7), 2: np.float64(90.4), 3: np.float64(88.2), 4: np.float64(94.89999999999999), 5: np.float64(87.0), 6: np.float64(53.1), 7: np.float64(93.5), 8: np.float64(97.0), 9: np.float64(93.0)}
------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.449 
Test Set (Epoch 2): Average loss: 1.5032, Accuracy: 8584/10000 (86%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[936.   1.  12.  10.   3.   4.   0.   3.  29.   2.]
 [ 22. 832.   1.   3.   1.   3.   0.   2.  29. 107.]
 [ 23.   0. 889.  30.  13.  27.   4.   6.   7.   1.]
 [  5.   0.  23. 875.  10.  69.   2.   4.  10.   2.]
 [  6.   0.  26.  20. 921.  15.   0.   8.   4.   0.]
 [  3.   0.  10.  88.  12. 876.   0.   6.   4.   1.]
 [ 17.   1. 219. 184.  56.  58. 413.   4.  36.  12.]
 [  4.   0.   4.  24.  24.  31.   0. 910.   1.   2.]
 [ 19.   1.   1.   1.   0.   0.   0.   0. 968.  10.]
 [ 12.   4.   1.   2.   0.   2.   0.   0.  15. 964.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(93.60000000000001), 1: np.float64(83.2), 2: np.float64(88.9), 3: np.float64(87.5), 4: np.float64(92.10000000000001), 5: np.float64(87.6), 6: np.float64(41.3), 7: np.float64(91.0), 8: np.float64(96.8), 9: np.float64(96.39999999999999)}

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 97.569 
Test Set (Epoch 3): Average loss: 1.5000, Accuracy: 8643/10000 (86%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[919.  10.  15.  11.   8.   0.   0.   4.  24.   9.]
 [  2. 970.   0.   1.   1.   2.   0.   0.   4.  20.]
 [ 21.   0. 869.  55.  27.  16.   3.   4.   4.   1.]
 [  6.   1.  15. 897.  22.  42.   4.   6.   4.   3.]
 [  1.   0.   9.  25. 940.   4.   1.  19.   1.   0.]
 [  3.   1.  12. 155.  10. 797.   0.  14.   4.   4.]
 [ 13.   8. 167. 200. 126.  39. 403.   5.  23.  16.]
 [  4.   0.   8.  18.  14.   8.   0. 944.   2.   2.]
 [ 16.  11.   6.   5.   0.   0.   0.   0. 954.   8.]
 [  3.  35.   1.   2.   0.   0.   0.   0.   9. 950.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(91.9), 1: np.float64(97.0), 2: np.float64(86.9), 3: np.float64(89.7), 4: np.float64(94.0), 5: np.float64(79.7), 6: np.float64(40.300000000000004), 7: np.float64(94.39999999999999), 8: np.float64(95.39999999999999), 9: np.float64(95.0)

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.913 
Test Set (Epoch 1): Average loss: 1.4834, Accuracy: 8873/10000 (89%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[948.   5.   7.   5.   1.   2.   4.   0.  14.  14.]
 [  1. 957.   2.   0.   1.   1.   1.   0.   4.  33.]
 [ 29.   0. 909.  16.  20.   9.  12.   0.   5.   0.]
 [  4.   1.  30. 864.  13.  59.  17.   0.   7.   5.]
 [  5.   0.  11.  22. 946.   5.  10.   1.   0.   0.]
 [  3.   1.  20.  68.  18. 885.   4.   0.   1.   0.]
 [  3.   0.  28.  26.   6.   4. 933.   0.   0.   0.]
 [ 25.   2.  75.  67. 158. 147.   6. 498.   8.  14.]
 [ 19.   7.   2.   1.   2.   0.   2.   0. 957.  10.]
 [  3.  13.   2.   1.   0.   0.   0.   0.   5. 976.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(94.8), 1: np.float64(95.7), 2: np.float64(90.9), 3: np.float64(86.4), 4: np.float64(94.6), 5: np.float64(88.5), 6: np.float64(93.30000000000001), 7: np.float64(49.8), 8: np.float64(95.7), 9: np.float64(97.6)}
-------------------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.462 
Test Set (Epoch 2): Average loss: 1.5107, Accuracy: 8458/10000 (85%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[936.   4.  11.   2.   0.   3.   9.   0.  31.   4.]
 [  5. 951.   0.   0.   1.   0.   1.   0.   7.  35.]
 [ 27.   0. 879.  19.  13.  10.  41.   2.   4.   5.]
 [ 14.   2.  26. 838.   5.  37.  65.   1.   5.   7.]
 [  8.   0.  26.  28. 886.   8.  29.   8.   5.   2.]
 [  6.   3.  19. 126.  11. 790.  36.   1.   3.   5.]
 [  2.   0.   9.   6.   3.   0. 977.   0.   2.   1.]
 [ 67.   5.  58.  93. 217. 218.  32. 271.   6.  33.]
 [ 19.   6.   2.   0.   0.   0.   5.   0. 957.  11.]
 [  5.  14.   2.   1.   0.   0.   1.   0.   4. 973.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(93.60000000000001), 1: np.float64(95.1), 2: np.float64(87.9), 3: np.float64(83.8), 4: np.float64(88.6), 5: np.float64(79.0), 6: np.float64(97.7), 7: np.float64(27.1), 8: np.float64(95.7), 9: np.float64(97.3)}
-------------------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 97.904 
Test Set (Epoch 3): Average loss: 1.5002, Accuracy: 8590/10000 (86%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[901.   6.  37.  12.  15.   1.   4.   1.  18.   5.]
 [  5. 958.   0.   2.   1.   0.   1.   0.  12.  21.]
 [ 13.   0. 885.  19.  44.  16.  18.   0.   5.   0.]
 [  4.   1.  22. 837.  32.  76.  22.   1.   3.   2.]
 [  1.   0.  10.   8. 966.   4.   4.   6.   1.   0.]
 [  4.   0.  15.  70.  26. 869.   5.  10.   1.   0.]
 [  5.   2.  16.  16.  16.   5. 940.   0.   0.   0.]
 [ 19.   4.  32.  56. 233. 293.   5. 347.   6.   5.]
 [ 15.   4.  11.   8.   2.   0.   4.   0. 952.   4.]
 [  8.  31.   2.   4.   1.   0.   2.   0.  17. 935.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(90.10000000000001), 1: np.float64(95.8), 2: np.float64(88.5), 3: np.float64(83.7), 4: np.float64(96.6), 5: np.float64(86.9), 6: np.float64(94.0), 7: np.float64(34.699999999999996), 8: np.float64(95.19999999999999), 9: np.float64(93.5)

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.856 
Test Set (Epoch 1): Average loss: 1.4815, Accuracy: 8843/10000 (88%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[960.   7.  13.   6.   3.   1.   1.   5.   0.   4.]
 [  3. 987.   1.   0.   0.   0.   1.   0.   0.   8.]
 [ 22.   0. 909.  17.  21.  11.  14.   6.   0.   0.]
 [  5.   2.  26. 867.  16.  55.  20.   8.   0.   1.]
 [  3.   0.  11.  19. 951.   4.  10.   2.   0.   0.]
 [  6.   1.  23.  68.  19. 858.   8.  16.   0.   1.]
 [  4.   1.  16.  26.   4.   2. 945.   1.   0.   1.]
 [  4.   2.   7.   9.  34.  10.   1. 930.   0.   3.]
 [278. 100.  17.  20.  10.   3.  31.   5. 505.  31.]
 [  5.  55.   1.   4.   2.   0.   0.   2.   0. 931.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(96.0), 1: np.float64(98.7), 2: np.float64(90.9), 3: np.float64(86.7), 4: np.float64(95.1), 5: np.float64(85.8), 6: np.float64(94.5), 7: np.float64(93.0), 8: np.float64(50.5), 9: np.float64(93.10000000000001)}
-------------------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.367 
Test Set (Epoch 2): Average loss: 1.5047, Accuracy: 8570/10000 (86%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[902.   2.  18.  16.   1.   5.  19.  12.   0.  25.]
 [  8. 940.   1.   6.   2.   1.   6.   2.   0.  34.]
 [ 14.   0. 844.  32.  16.  19.  58.  16.   0.   1.]
 [  4.   0.  15. 879.   6.  52.  28.  15.   0.   1.]
 [  4.   0.  14.  42. 873.  23.  19.  24.   0.   1.]
 [  2.   0.  10. 107.   7. 843.  14.  17.   0.   0.]
 [  3.   0.   2.  13.   2.   2. 977.   1.   0.   0.]
 [  3.   0.   4.  14.   6.  17.   3. 949.   0.   4.]
 [272.  36.  18.  77.   7.   3.  69.   9. 404. 105.]
 [  5.  19.   1.  11.   0.   2.   2.   1.   0. 959.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(90.2), 1: np.float64(94.0), 2: np.float64(84.39999999999999), 3: np.float64(87.9), 4: np.float64(87.3), 5: np.float64(84.3), 6: np.float64(97.7), 7: np.float64(94.89999999999999), 8: np.float64(40.400000000000006), 9: np.float64(95.89

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 97.698 
Test Set (Epoch 3): Average loss: 1.4972, Accuracy: 8634/10000 (86%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[941.   7.  23.   4.   6.   3.   4.   6.   0.   6.]
 [  6. 979.   2.   0.   0.   1.   1.   0.   0.  11.]
 [ 20.   0. 902.  19.  16.  17.  21.   5.   0.   0.]
 [ 10.   4.  50. 814.  12.  64.  30.  14.   0.   2.]
 [  3.   0.  29.  16. 904.  16.  15.  17.   0.   0.]
 [  4.   0.  26.  64.  12. 871.  10.  12.   0.   1.]
 [  7.   0.  20.   9.   3.   1. 959.   1.   0.   0.]
 [  7.   0.  13.  11.  14.  28.   4. 923.   0.   0.]
 [293. 117.  40.  16.   4.  11.  54.   9. 421.  35.]
 [ 10.  59.   2.   1.   0.   1.   4.   3.   0. 920.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(94.1), 1: np.float64(97.89999999999999), 2: np.float64(90.2), 3: np.float64(81.39999999999999), 4: np.float64(90.4), 5: np.float64(87.1), 6: np.float64(95.89999999999999), 7: np.float64(92.30000000000001), 8: np.float64(42.1), 9: np.f

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.858 
Test Set (Epoch 1): Average loss: 1.4764, Accuracy: 8777/10000 (88%)
------------------------------
Test Set (Epoch 1) Confusion Matrix 
[[920.   8.  23.   9.   6.   1.   5.   2.  26.   0.]
 [  3. 989.   0.   0.   0.   0.   1.   0.   6.   1.]
 [ 24.   0. 919.  11.  23.   8.  10.   3.   2.   0.]
 [  3.   2.  39. 841.  12.  79.  14.   6.   4.   0.]
 [  6.   0.  17.  11. 945.   8.  11.   2.   0.   0.]
 [  6.   2.  25.  52.  15. 884.   4.  10.   2.   0.]
 [  1.   0.  33.  23.   3.   5. 935.   0.   0.   0.]
 [  9.   2.  16.  15.  34.  22.   3. 898.   1.   0.]
 [ 20.  13.   9.   2.   0.   0.   3.   0. 953.   0.]
 [ 28. 394.   9.  14.   0.   1.   5.   3.  53. 493.]]
------------------------------
Test Set (Epoch 1) Class Wise ACC 
{0: np.float64(92.0), 1: np.float64(98.9), 2: np.float64(91.9), 3: np.float64(84.1), 4: np.float64(94.5), 5: np.float64(88.4), 6: np.float64(93.5), 7: np.float64(89.8), 8: np.float64(95.3), 9: np.float64(49.3)}
------------------------------
Test Se

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.484 
Test Set (Epoch 2): Average loss: 1.4909, Accuracy: 8590/10000 (86%)
------------------------------
Test Set (Epoch 2) Confusion Matrix 
[[913.   2.  14.   8.   3.   3.   8.   5.  44.   0.]
 [  6. 959.   0.   1.   0.   0.   2.   2.  17.  13.]
 [ 20.   0. 855.  30.  29.  22.  31.   7.   6.   0.]
 [  6.   0.  12. 838.  11.  85.  26.  11.  11.   0.]
 [  5.   0.  11.  23. 913.  18.  14.  12.   4.   0.]
 [  7.   0.   8.  75.  14. 871.  12.  13.   0.   0.]
 [  3.   0.   5.  18.   4.   7. 962.   0.   1.   0.]
 [  5.   0.   2.  18.  12.  17.   2. 943.   1.   0.]
 [ 10.   1.   2.   6.   0.   2.   0.   0. 976.   3.]
 [ 81. 330.   4.  30.   2.   2.  13.  36. 142. 360.]]
------------------------------
Test Set (Epoch 2) Class Wise ACC 
{0: np.float64(91.3), 1: np.float64(95.89999999999999), 2: np.float64(85.5), 3: np.float64(83.8), 4: np.float64(91.3), 5: np.float64(87.1), 6: np.float64(96.2), 7: np.float64(94.3), 8: np.float64(97.6), 9: np.float64(36.0)}
-------------------------

/usr/local/lib/python3.12/dist-packages/torch/nn/_reduction.py:60: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  return get_enum(legacy_get_string(size_average, reduce, emit_warning))


 * Acc@1 98.144 
Test Set (Epoch 3): Average loss: 1.4945, Accuracy: 8512/10000 (85%)
------------------------------
Test Set (Epoch 3) Confusion Matrix 
[[902.   8.  20.   0.   5.   3.   3.   2.  52.   5.]
 [  5. 973.   0.   0.   1.   0.   0.   0.  10.  11.]
 [ 13.   1. 917.  22.  19.   7.  12.   1.   8.   0.]
 [ 18.   4.  35. 838.  15.  67.  11.   2.  10.   0.]
 [  3.   1.  18.  25. 930.   9.   5.   5.   4.   0.]
 [  5.   4.  26.  67.  18. 865.   7.   6.   2.   0.]
 [  4.   1.  20.  28.   9.   4. 930.   2.   2.   0.]
 [ 14.   1.   9.  23.  33.  26.   3. 886.   5.   0.]
 [  8.   4.   5.   0.   0.   0.   0.   0. 975.   8.]
 [ 67. 405.   5.   9.   0.   0.   3.   1. 214. 296.]]
------------------------------
Test Set (Epoch 3) Class Wise ACC 
{0: np.float64(90.2), 1: np.float64(97.3), 2: np.float64(91.7), 3: np.float64(83.8), 4: np.float64(93.0), 5: np.float64(86.5), 6: np.float64(93.0), 7: np.float64(88.6), 8: np.float64(97.5), 9: np.float64(29.599999999999998)}
------------------------